import Link from "next/link";
import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.css'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar/Navbar';
import Providers from "@/components/Providers";


import '@fortawesome/free-solid-svg-icons'
// import  {ThemeProvider}  from "@/context/ThemContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         >
      <Providers>
       {/* <ThemeProvider> */}
       <div className="container">
           {/* <Navbar /> */}
          <div className="fullheight"></div>
        {children}
          {/* <Footer /> */}
        </div>
       {/* </ThemeProvider> */}
      </Providers>
       
      </body>
    </html>
  );
}
